[20410] Remove Data-Sharing option
eProsima/Shapes-Demo-Docs pull request #100
Opened 2024-02-29 11:31 UTC by JesusPoderoso

Shapes Demo has never worked in data-sharing mode (because the Shape type contains an unbounded string).
This PR removes the data-sharing option from the documentation, as it is never used.

https://github.com/Mergifyio backport 2.6.x 2.10.x 2.11.x 2.12.x 2.13.x

2024-03-18 10:19 UTC, EduPonz requested changes
This PR should also update screenshots (see for example [this one](https://eprosima-shapes-demo.readthedocs.io/en/latest/first_steps/first_steps.html#participant-configuration))

2024-03-18 12:12 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=180)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/180/)

2024-03-18 15:26 UTC, EduPonz approved these changes

2024-03-18 15:27 UTC, merged

2024-03-19 15:23 UTC, elianalf commented
@Mergifyio backport 2.6.x 2.10.x 2.12.x 2.13.x