[21890] Update commercial support section in project README
eProsima/Shapes-Demo-Docs pull request #138
Opened 2024-10-15 09:46 UTC by JesusPoderoso

## Description

This PR updates the Shapes Demo docs README's commercial support section

@Mergifyio backport 3.0.x 2.14.x 2.10.x 2.6.x

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** Documentation tests pass locally.
- [x] Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [x] The title and description correctly express the PR's purpose.
- **N/A** Check contributor checklist is correct.
- **N/A** CI passes without warnings or errors.

2024-10-15 09:47 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=232)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/232/)

2024-10-17 06:13 UTC, LuciaEchevarria99 requested changes

2024-10-17 06:13 UTC, LuciaEchevarria99 commented on README.md
The title `Commercial Support` seems to overlap with the eProsima logo. Could we add more space so that `Commercial Support` moves underneath the logo?

2024-10-17 07:03 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=233)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/233/)

2024-10-17 07:08 UTC, LuciaEchevarria99 approved these changes
LGTM

2024-10-17 07:09 UTC, merged