[17831] Bump version to v2.8.2
eProsima/Shapes-Demo-Docs pull request #54
Opened 2023-04-13 15:36 UTC by Mario-DL

2023-04-13 15:37 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=97)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/97/)

2023-04-13 19:37 UTC, jsantiago-eProsima requested changes

2023-04-13 19:37 UTC, jsantiago-eProsima commented on docs/notes/previous_versions/v2.8.1.rst
> +* Support for Fast DDS v2.8.1
Newline at the end of file

2023-04-14 05:27 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=98)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/98/)

2023-04-14 07:37 UTC, jsantiago-eProsima approved these changes

2023-04-14 07:39 UTC, merged