[19325] Bump to 2.11.2 and release notes
eProsima/Shapes-Demo-Docs pull request #67
Opened 2023-08-09 09:47 UTC by Mario-DL

2023-08-09 09:48 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=118)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/118/)

2023-08-09 09:50 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=119)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/119/)

2023-08-10 20:02 UTC, EduPonz requested changes

2023-08-10 20:02 UTC, EduPonz commented on docs/notes/previous_versions/v2.11.1.rst
> +==============
Please underline with `^`

2023-08-11 06:30 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=120)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/120/)

2023-08-11 07:52 UTC, EduPonz approved these changes

2023-08-11 07:53 UTC, EduPonz approved these changes

2023-08-11 07:53 UTC, merged