[20176] Bump version to 2.12.1
eProsima/Shapes-Demo-Docs pull request #76
Opened 2023-12-22 13:00 UTC by MiguelCompany

2023-12-22 13:02 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=134)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/134/)

2023-12-22 13:22 UTC, cferreiragonz approved these changes

2024-01-11 11:12 UTC, JesusPoderoso requested changes

2024-01-11 11:12 UTC, JesusPoderoso commented on docs/notes/notes.rst
> +* Statistics and monitor are enabled by default
Include latest PRs merged
```suggestion
* Statistics and monitor service are enabled by default
* Introduced new UDP transport that intentionally drops a percentage of samples
* Downgrade CMake minimum required version
* Regenerate Shapes types with Fast DDS-Gen v3.2.1 
```

2024-01-12 08:11 UTC, JesusPoderoso approved these changes
LGTM

2024-01-12 08:13 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=139)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/139/)

2024-01-12 08:14 UTC, merged