Udp sample loss feature
eProsima/Shapes-Demo-Docs pull request #77
Opened 2023-12-22 13:14 UTC by elianalf

Sample loss mode and example

2023-12-22 13:16 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=135)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/135/)

2024-01-09 09:08 UTC, JesusPoderoso requested changes

2024-01-09 09:08 UTC, JesusPoderoso commented on docs/examples/sample_loss.rst
> +================================
Fit title undeline
```suggestion
Udp Sample Loss modality
========================
```

2024-01-09 11:30 UTC, JesusPoderoso approved these changes
LGTM with green CI

2024-01-09 11:41 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=136)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/136/)

2024-01-09 11:47 UTC, JesusPoderoso requested changes
Please, update also all the sceenshots to display both "Active Statistics" & "Active Monitor Service" as checked

2024-01-10 11:40 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=138)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/138/)

2024-01-10 11:55 UTC, JesusPoderoso approved these changes
LGTM

2024-01-11 11:10 UTC, merged