[20023] Bump version to v2.10.3
eProsima/Shapes-Demo-Docs pull request #80
Opened 2024-01-16 14:47 UTC by JesusPoderoso

2024-01-16 15:34 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=141)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/141/)

2024-01-18 14:22 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=153)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/153/)

2024-01-18 14:37 UTC, EduPonz requested changes

2024-01-18 14:37 UTC, EduPonz commented on docs/notes/previous_versions/v2.10.1.rst
> +This patch release includes the following **improvements**:
```suggestion

This patch release includes the following **improvements**:
```

2024-01-18 14:37 UTC, EduPonz commented on docs/notes/previous_versions/v2.10.2.rst
> +This patch release includes the following **improvements**:
```suggestion

This patch release includes the following **improvements**:
```

2024-01-22 06:51 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=154)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/154/)

2024-01-26 10:41 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=164)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/164/)

2024-01-30 15:29 UTC, MiguelCompany approved these changes

2024-01-31 15:20 UTC, merged