[20414] Bump version to 2.14.0
eProsima/Shapes-Demo-Docs pull request #99
Opened 2024-02-26 07:20 UTC by JesusPoderoso

## Description

This PR:
* [x] Bumps version to 2.14.0 in consonance with eProsima/Fast-DDS#4439
* [x] Updates the mirror workflow to mirror master in 2.14.x
* [x] Adds this PR template  

## Contributor Checklist

- [x] Commit messages follow the project guidelines. 
- **N/A** Documentation tests pass locally.
- **N/A** Applicable backports have been included in the description.

## Reviewer Checklist

- [x] The PR has a milestone assigned.
- [ ] The title and description correctly express the PR's purpose.
- [ ] Check contributor checklist is correct.
- [ ] CI passes without warnings or errors.

2024-02-26 07:22 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=175)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/175/)

2024-03-19 07:28 UTC, EduPonz requested changes
NIT

2024-03-19 08:22 UTC, richiprosima commented
Build status: [![Build Status](http://jenkins.eprosima.com:8080/buildStatus/icon?job=shapes_demo_docs_manual&build=181)](http://jenkins.eprosima.com:8080/job/shapes_demo_docs_manual/181/)

2024-03-19 11:45 UTC, EduPonz approved these changes

2024-03-19 11:45 UTC, merged